import { expect, loginAs, test } from "./fixtures";

test.beforeEach(async ({ resetDemo }) => { await resetDemo(); });
test.afterEach(async ({ browserDiagnostics }) => { await browserDiagnostics.assertNoErrors(); });

test("note confirmation preserves thoughts and a frozen snapshot through progress updates and owner edits", async ({ page }, testInfo) => {
  await loginAs(page, 3, "/profile/library");
  const data = await (await page.request.get("/api/bootstrap")).json();
  const book = data.users.find((user: { id: number }) => user.id === 3).books[0];
  const bookId = book.catalogBookId ?? book.id;
  const changed = await page.request.patch(`/api/books/${bookId}`, { data: { readingStatus: "reading", pagesCurrent: 40, pagesTotal: 100, progressUnit: "pages", readingComment: "Первая мысль\nПолный текст заметки" } });
  expect(changed.ok()).toBeTruthy();
  await page.goto(`/books/${bookId}`);
  const personal = page.getByTestId("book-personal-state");
  const thoughts = personal.getByRole("textbox", { name: "Мысли, цитаты, впечатления" });
  await expect(thoughts).toHaveValue("Первая мысль\nПолный текст заметки");
  await personal.getByRole("button", { name: "Сохранить заметку", exact: true }).click();
  const confirm = page.getByRole("dialog", { name: "Сохранить заметку?", exact: true });
  await expect(confirm).toContainText("Страницы: 40 из 100 (40%)");
  await expect(confirm.locator(".book-note-body")).toHaveText("Первая мысль\nПолный текст заметки");
  await confirm.getByRole("button", { name: "Отмена", exact: true }).click();
  await expect(thoughts).toHaveValue("Первая мысль\nПолный текст заметки");
  await personal.getByRole("button", { name: "Сохранить заметку", exact: true }).click();
  await confirm.getByRole("button", { name: "Сохранить", exact: true }).click();
  await expect(confirm).toBeHidden();
  await expect(thoughts).toHaveValue("Первая мысль\nПолный текст заметки");
  await page.getByRole("button", { name: "Заметки", exact: true }).click();
  const note = page.locator(".book-note-card");
  await expect(note).toHaveCount(1);
  await expect(note).toContainText("40 из 100 (40%)");
  await personal.getByRole("spinbutton", { name: "Страницы: прочитано", exact: true }).fill("60");
  await expect(page.getByTestId("reading-autosave-status")).toHaveText("Сохранено");
  await expect(note).toContainText("40 из 100 (40%)");
  await note.getByRole("button", { name: "Редактировать", exact: true }).click();
  await note.getByRole("textbox", { name: "Текст заметки" }).fill("Исправленная мысль");
  await note.getByRole("button", { name: "Сохранить", exact: true }).click();
  await expect(note.locator(".book-note-body")).toHaveText("Исправленная мысль");
  await expect(note).toContainText("40 из 100 (40%)");
  await expect(note.getByRole("button", { name: /Нравится|Комментировать|Отправить/ })).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath(`notes-${testInfo.project.name}.png`), fullPage: true });
  page.once("dialog", (dialog) => dialog.accept());
  await note.getByRole("button", { name: "Удалить", exact: true }).click();
  await expect(note).toHaveCount(0);
});

test("a viewer at forty percent never receives the forty-one percent note and read unlocks it", async ({ page }) => {
  await loginAs(page, 3, "/profile/library");
  const data = await (await page.request.get("/api/bootstrap")).json();
  const book = data.users.find((user: { id: number }) => user.id === 3).books[0];
  const bookId = book.catalogBookId ?? book.id;
  await loginAs(page, 1);
  const added = await page.request.post("/api/books", { data: { useExistingId: bookId, readingStatus: "reading", chaptersCurrent: 0, chaptersTotal: 100, progressUnit: "chapters" } });
  expect(added.ok()).toBeTruthy();
  expect((await page.request.post(`/api/books/${bookId}/notes`, { data: { body: "Доступная нулевая заметка" } })).ok()).toBeTruthy();
  expect((await page.request.patch(`/api/books/${bookId}`, { data: { chaptersCurrent: 41, chaptersTotal: 100, progressUnit: "chapters" } })).ok()).toBeTruthy();
  expect((await page.request.post(`/api/books/${bookId}/notes`, { data: { body: "Секрет на сорок первом проценте" } })).ok()).toBeTruthy();
  await loginAs(page, 3);
  expect((await page.request.patch(`/api/books/${bookId}`, { data: { readingStatus: "reading", chaptersCurrent: 40, chaptersTotal: 100, progressUnit: "chapters" } })).ok()).toBeTruthy();
  await page.goto(`/books/${bookId}`);
  await page.getByRole("button", { name: "Заметки", exact: true }).click();
  await page.getByRole("button", { name: "Все заметки", exact: true }).click();
  await expect(page.locator(".book-note-card")).toHaveCount(1);
  await expect(page.locator(".book-note-card")).toContainText("Доступная нулевая заметка");
  const gated = await (await page.request.get(`/api/books/${bookId}/notes?scope=all`)).text();
  expect(gated).not.toContain("Секрет на сорок первом проценте");
  const now = new Date();
  expect((await page.request.patch(`/api/books/${bookId}`, { data: { readingStatus: "read", rating: 4, shortReview: "Прочитано", readMonth: now.getMonth() + 1, readYear: now.getFullYear() } })).ok()).toBeTruthy();
  await page.reload();
  await page.getByRole("button", { name: "Заметки", exact: true }).click();
  await page.getByRole("button", { name: "Все заметки", exact: true }).click();
  await expect(page.locator(".book-note-card")).toHaveCount(2);
  await expect(page.locator(".book-note-card").filter({ hasText: "Секрет на сорок первом проценте" })).toBeVisible();
  await expect(page.locator(".book-note-card").first().getByRole("button", { name: "Пожаловаться", exact: true })).toBeVisible();
});
