CREATE TABLE IF NOT EXISTS wishlist_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  catalog_book_id BIGINT UNSIGNED NULL,
  author VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  genres LONGTEXT NOT NULL,
  annotation TEXT NOT NULL,
  cover_path VARCHAR(1000) NULL,
  cover_tone VARCHAR(30) NOT NULL DEFAULT 'blue',
  marketplace VARCHAR(30) NOT NULL,
  product_url VARCHAR(1000) NOT NULL,
  pickup_address VARCHAR(500) NOT NULL,
  recipient_phone VARCHAR(50) NOT NULL,
  price_amount DECIMAL(12,2) NULL,
  price_currency VARCHAR(10) NOT NULL DEFAULT 'KZT',
  price_checked_at DATETIME NULL,
  reserved_by_user_id BIGINT UNSIGNED NULL,
  reserved_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY wishlist_user_idx (user_id, created_at),
  KEY wishlist_catalog_book_idx (catalog_book_id),
  KEY wishlist_reserved_by_idx (reserved_by_user_id),
  CONSTRAINT wishlist_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT wishlist_catalog_book_fk FOREIGN KEY (catalog_book_id) REFERENCES books(id) ON DELETE SET NULL,
  CONSTRAINT wishlist_reserved_by_fk FOREIGN KEY (reserved_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
